# Generated by Django 2.1.5 on 2019-01-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttendanceStatusName', models.CharField(max_length=255)),
                ('AttendanceStatusDesc', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('courseCode', models.CharField(max_length=255)),
                ('courseStudentKey', models.CharField(max_length=255)),
                ('courseTeacherKey', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyAttendanceAttendanceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(max_length=255)),
                ('institutionCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255)),
                ('studentCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('studentInstitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=255)),
                ('teacherCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('teacherInstitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='dailyAttendanceStudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Student'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='dailyAttendanceStudentStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.AttendanceStatus'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseInstitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Institution'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendanceCourseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_course', to='IPC.Course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendanceTeacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taker', to='IPC.Teacher'),
        ),
    ]
