# Generated by Django 2.1.5 on 2019-01-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancestatus',
            old_name='AttendanceStatusDesc',
            new_name='attendanceStatusDesc',
        ),
        migrations.RenameField(
            model_name='attendancestatus',
            old_name='AttendanceStatusName',
            new_name='attendanceStatusName',
        ),
    ]
