# Generated by Django 2.1.5 on 2019-01-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0002_auto_20190122_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcementDate', models.DateTimeField(auto_now_add=True)),
                ('announcementFeed', models.TextField(max_length=4000)),
                ('announcementCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('announcementPosterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Teacher')),
            ],
        ),
    ]
