# Generated by Django 2.1.5 on 2019-02-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0003_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseStudentKey',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseTeacherKey',
        ),
    ]
