# Generated by Django 2.1.5 on 2019-02-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0004_auto_20190209_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentCourse',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentInstitution',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacherCourse',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacherInstitution',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcementPosterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceTeacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='dailyAttendanceStudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
