# Generated by Django 2.1.5 on 2019-02-10 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0005_auto_20190210_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='attendanceStatusName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
