# Generated by Django 2.1.5 on 2019-02-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0008_auto_20190218_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='dailyAttendanceStudentStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.AttendanceStatus'),
        ),
    ]
