# Generated by Django 2.1.5 on 2019-02-19 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPC', '0009_auto_20190218_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultStudentMark', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('resultFeedback', models.TextField(max_length=4000)),
                ('resultReturnedDate', models.DateTimeField(auto_now_add=True)),
                ('resultName', models.CharField(max_length=255)),
                ('resultCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('resultStudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResultTypeName', models.CharField(max_length=255)),
                ('ResultTypeDesc', models.TextField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='resultType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.ResultType'),
        ),
    ]
