# Generated by Django 2.1.5 on 2019-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0010_auto_20190219_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='resultFeedback',
            field=models.CharField(max_length=255),
        ),
    ]
