# Generated by Django 2.1.5 on 2019-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0011_auto_20190220_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='resultFeedback',
            field=models.CharField(default='', max_length=255),
        ),
    ]
