# Generated by Django 2.1.5 on 2019-02-20 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPC', '0012_auto_20190220_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarDate', models.DateTimeField(auto_now_add=True)),
                ('calendarFeed', models.TextField(max_length=4000)),
                ('calendarHeading', models.CharField(max_length=255)),
                ('calendarCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('calendarPosterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
