# Generated by Django 2.1.5 on 2019-02-20 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0013_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='calendarDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 19, 58, 13, 198383)),
        ),
    ]
