# Generated by Django 2.1.5 on 2019-02-27 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPC', '0014_calendar_calendarduedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssigntmentDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigntmentDeadlineDatePosted', models.DateTimeField(auto_now_add=True)),
                ('assigntmentDeadlineMemo', models.TextField(max_length=4000)),
                ('assigntmentDeadlineTitle', models.CharField(max_length=255)),
                ('assigntmentDeadlineDueDate', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 39, 48, 729628))),
                ('assigntmentDeadlineCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('assigntmentDeadlinePosterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examDateDatePosted', models.DateTimeField(auto_now_add=True)),
                ('examDateMemo', models.TextField(max_length=4000)),
                ('examDateTitle', models.CharField(max_length=255)),
                ('examDateDate', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 39, 48, 729628))),
                ('examDateCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('examDatePosterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=255)),
                ('subjectCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('subjectTeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='calendarCourse',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='calendarPosterId',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
