# Generated by Django 2.1.5 on 2019-02-27 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0015_auto_20190227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 43, 30, 934499)),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='examDateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 43, 30, 935481)),
        ),
    ]
