# Generated by Django 2.1.5 on 2019-02-27 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0016_auto_20190227_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendanceSubject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPC.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='resultSubject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='IPC.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 45, 25, 656693)),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='examDateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 15, 45, 25, 656693)),
        ),
    ]
