# Generated by Django 2.1.5 on 2019-02-27 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0017_auto_20190227_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 22, 25, 460479)),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='examDateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 22, 25, 460479)),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultFeedback',
            field=models.CharField(default='Keep up the good work', max_length=255),
        ),
    ]
