# Generated by Django 2.1.5 on 2019-02-27 16:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0018_auto_20190227_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 30, 2, 841152)),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='examDateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 30, 2, 842122)),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultFeedback',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultStudentMark',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
