# Generated by Django 2.1.5 on 2019-02-27 16:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0021_auto_20190227_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 33, 15, 226588)),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='examDateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 16, 33, 15, 226588)),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultStudentMark',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
