# Generated by Django 2.1.5 on 2019-02-27 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0023_auto_20190227_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcementDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineDueDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 20, 29, 43, 758121)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='examDateDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 20, 29, 43, 758121)),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultReturnedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
