# Generated by Django 2.1.5 on 2019-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0025_auto_20190227_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlineCourse',
        ),
        migrations.RemoveField(
            model_name='assigntmentdeadline',
            name='assigntmentDeadlinePosterId',
        ),
        migrations.RemoveField(
            model_name='examdate',
            name='examDateCourse',
        ),
        migrations.RemoveField(
            model_name='examdate',
            name='examDatePosterId',
        ),
        migrations.DeleteModel(
            name='AssigntmentDeadline',
        ),
        migrations.DeleteModel(
            name='ExamDate',
        ),
    ]
