# Generated by Django 2.1.5 on 2019-03-11 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPC', '0027_auto_20190311_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='materialCourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPC.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='materialPosterId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='materialSubject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPC.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='materialTitle',
            field=models.CharField(max_length=255),
        ),
    ]
