# Generated by Django 2.1.5 on 2019-03-13 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPC', '0028_auto_20190311_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussionPost', models.TextField(max_length=4000)),
                ('discussionCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('discussionUpdatedTime', models.DateTimeField(null=True)),
                ('discussionCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Course')),
                ('discussionMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Material')),
                ('discussionPostUpdatere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL)),
                ('discussionPoster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
