# Generated by Django 2.1.5 on 2019-03-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0029_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='discussionPostUpdatere',
        ),
    ]
