# Generated by Django 2.1.5 on 2019-03-23 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0030_remove_discussion_discussionpostupdatere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='resultStudentMark',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
