# Generated by Django 2.1.5 on 2019-03-23 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0031_auto_20190323_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='resultStudentMark',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
