# Generated by Django 2.1.5 on 2019-03-29 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPC', '0034_result_resultoverallvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forumTopicName', models.CharField(max_length=255)),
                ('forumTopicPostedDate', models.DateTimeField(auto_now_add=True)),
                ('forumTopicInstitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.Institution')),
                ('forumTopicPoster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumTopicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forumTopicPostPost', models.TextField(max_length=4000)),
                ('forumTopicPostCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('forumTopicPostUpdatedTime', models.DateTimeField(null=True)),
                ('forumTopicPostPoster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forumTopicPostTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPC.ForumTopic')),
            ],
        ),
    ]
