# Generated by Django 2.1.5 on 2019-03-29 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0036_forumtopic_forumtopicdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='forumTopicFlag',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
