# Generated by Django 2.1.5 on 2019-03-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0038_forumtopic_forumtopiccourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='forumTopicCourse',
        ),
    ]
