# Generated by Django 2.1.5 on 2019-03-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0039_remove_forumtopic_forumtopiccourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='forumTopicCourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPC.Course'),
            preserve_default=False,
        ),
    ]
