# Generated by Django 2.1.5 on 2019-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0040_forumtopic_forumtopiccourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='resultFeedback',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
