# Generated by Django 2.1.5 on 2019-04-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPC', '0043_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
